AppTwo/urls.py
from django.urls import re_path as url
from AppTwo import views

app_name = 'AppTwo'

urlpatterns = [
    url(r'^registrations/$', views.register, name='registrations'),
    url(r'^user_login/$', views.user_login, name='user_login')
    
]

ProTwo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from AppTwo import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('AppTwo/', include('AppTwo.urls')),
    path('logout/', views.user_logout, name="logout"),
    path('special/', views.special, name='special'),

]

AppTwo/models.py
from pyexpat import model
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    portfolio_site = models.URLField(blank=True)
    
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

AppTwo/forms.py
from pyexpat import model
from django import forms
from AppTwo.models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email','password')
        
class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields =('portfolio_site', 'profile_pic')

AppTwo/views.py
import imp
from multiprocessing import context
from django.shortcuts import render
from django.http import HttpResponse
from AppTwo.models import User
from AppTwo.forms import UserForm, UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout

# Create your views here.

def index(request):
    return render(request, 'AppTwo/index.html')

def special(request):
    return HttpResponse("Nice!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))

def register(request):
    
    registered = False 
    
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        
        if user_form.is_vaid() and profile_form.is_valid():
        
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            
            profile = profile_form.save(commit=False)
            
            profile.user = user
            
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
                
                
            profile.save()
            
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
        
    return render(request, 'AppTwo/registrations.html', {'user_from':user_form, 'profile_form':profile_form, 'registered':registered})



def user_login(request):
    
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.gte('password')
        
        user = authentication(username=username, password=password)
        
        if user:
            if user.is_activate:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to login and failed")
            print("Username: {} and password ()".format(username,password))
            return HttpResponse("Inavlid login details supplied")
    else:
        return render(request, "AppTwo/login.html",{})
    

templates/AppTwo/base.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    </head>
    <body>
        <nav class='navbar navbar-default'>
            <div class='container'>
                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand" href="{%url 'index' %}">Home</a></li>
                    <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                    <li><a class="navbar-brand" href="{% url 'AppTwo:registrations'%}">Register</a></li>

                    {% if user.is_authenticated %}
                    <li><a class='navbar-link' href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                    <li><a class="navbar-link" href="{% url 'basic_app:user_login'%}">Login</a></li>
                    {% endif %}

                </ul>
            </div>
        </nav>

            {%block body_block%}
            {% endblock %}
        <script src="" async defer></script>
    </body>
</html>

templates/AppTwo/index.html
{% extends "AppTwo/base.html" %}
{% block body_block %}

<div class="jumbotron">
<h1>Django Home Page</h1>
</div>

{% endblock %}

templates/AppTwo/login.html
{% extends 'AppTwo/base.html' %}
{% block body_block %}

<div class='jumbotron'>
    <h1>Please login</h1>
    <form action="{% url 'AppTwo:user_login' %}" method="post">
        {% csrf_token%}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="password" name="password">
        
        <input type="submit" name="" value="Login">
</div>

templates/AppTwo/registrations.html
{% extends 'AppTwo/base.html' %}
{% load static %}

{% block body_block %}

<div class="jumbotron">
    {% if registered %}
    <h1>Thanks for registering</h1>
    {% else %}
    <h1>Register here!</h1>
    <h3>Fill out the form: </h3>

    <form  enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ user_form.as_p}}
    {{ profile_form.as_p}}
    <input type="submit" value="Register">
    </form>
    {% endif %}

{% endblock %}